spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        git:
          enabled: false
        bootstrap: false

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: config-service
