apiVersion: v1
kind: Namespace
metadata:
  name: pulsecare
  labels:
    name: pulsecare
    app: pulsecare-telehealth
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pulsecare-quota
  namespace: pulsecare
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    pods: "50"
