spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/voxcare
    username: voxcare
    password: voxcare123

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: voice-service

voxcare:
  voice:
    patient-service-base-url: http://patient-service:8082
    provider-service-base-url: http://provider-service:8083
    appointment-service-base-url: http://appointment-service:8084
    sms-fallback-booking-url: ${SMS_FALLBACK_BOOKING_URL:http://localhost:3001/appointments}
