spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/pulsecare
    username: pulsecare
    password: pulsecare123

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: voice-service
